# Generated by Django 3.2.6 on 2021-08-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacTipoId', models.CharField(max_length=3)),
                ('pacNumId', models.CharField(max_length=20)),
                ('pacNombre', models.CharField(max_length=255)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=255)),
                ('tipoIdentificacion', models.CharField(max_length=255)),
                ('numeroIdentificacion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('profesion', models.CharField(blank=True, max_length=255, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=255, null=True)),
                ('registroMedico', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('numeroIdentificacion', 'tipoIdentificacion')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('codServicio', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombreServicio', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=20)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AddField(
            model_name='attentions',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='historia_clinica.professional'),
        ),
        migrations.AddField(
            model_name='attentions',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='historia_clinica.service'),
        ),
    ]
